### ISSUE TITLE
Swiften_Boost is not built when the libboost debian packages are installed

### ISSUE THREAD

**Issue by LNJ2** [swift/swift#34] opened 2016-11-16 08:03 UTC
I tried to built swiften 3.0, but it didn't built `3rdParty/Boost/libSwiften_Boost.a`, because I had the debian packages for boost installed, but these packages do NOT include Swiften_Boost, so I couldn't build my project. (I removed libboost-all-dev on my system, now, but it would be nice if this could be fixed)

**Comment by vitalyster** [comment] 2016-11-16 10:50
You should get actual linker flags from `swiften-config` output and should not link Swiften_Boost explicitly

**Comment by LNJ2** [comment] 2016-11-16 13:01
I HAVE used the actual linker flags, But Swiften_Boost was not built.

**Comment by vitalyster** [comment] 2016-11-16 13:02
It is intended, linker flags will have references to system boost in this case

**Comment by LNJ2** [comment] 2016-11-16 13:04
Yeah, but my system had no Swiften_Boost, it only had Boost and Swiften_Boost was not builded.

**Comment by tfar** [comment] 2016-11-16 13:05
What does the scons config output look like?

**Comment by vitalyster** [comment] 2016-11-16 13:08
@LNJ2 if you have uninstalled system boost, then you need to rebuild Swiften, `scons` will re-check Boost presence and will enable building and linking bundled boost copy

**Comment by LNJ2** [comment] 2016-11-16 13:10
## Just to calrify: Everything is working for me
I just want to say that when the boost packages are installed on my system, it won't build Swiften_Boost.

I have removed the libboost packages from my system and then Boost and SwiftenBoost were built.
Just install `libboost-all-dev` (on debian sid) and you will get the same as I had.

**Comment by LNJ2** [comment] 2016-11-16 13:11
@vitalyster I know I have to rebuild it.

**Comment by vitalyster** [comment] 2016-11-16 13:12
@LNJ2 building bundled boost is a "last resort" when scons is unable to find system one

**Comment by LNJ2** [comment] 2016-11-16 13:14
@vitalyster You might wonder, but I also know that.

**Comment by tfar** [comment] 2016-11-16 13:21
@LNJ2 So what is the actual issue here? The build of Swiften fails if only some boost dependencies are installed?

**Comment by LNJ2** [comment] 2016-11-16 13:27
@tfar Why is scons (or whatever) not building Swiften_Boost, if this part is missing?

**Comment by vitalyster** [comment] 2016-11-16 14:53
@LNJ2 your actual problem still isn't clear. `scons` checks at configure time presence of boost and prefer system one, it shouldn't build Swiften_Boost when system one is present, it's by design.

**Comment by Kev** [comment] 2016-11-17 09:50
Hi there,
To check that I understand your problem correctly:
1) You have your own application that uses libSwiften
2) You compiled Swiften on a system that has the system Boost installed
3) Building Swiften did not generate libSwiften_Boost
4) Your application failed to link, because your build system tries to link against libSwiften_Boost.
(And then you uninstalled the system Boost, rebuilt Swiften, it built libSwiften_Boost, and your build system was happy)

Is that right?

**Comment by LNJ2** [comment] 2016-11-17 13:41
@Kev That's exactly what I did (to be exact, someone else of my 'team' created the project and I tried to build it).

I think I can understand you now ... libBoost and libSwiften_Boost are the same, but have different names? (I thought that Swiften_Boost would be something like an 'extension' for Boost ...)

**Comment by Kev** [comment] 2016-11-17 15:02
Yes, Swiften_Boost is the name of the boost library if Swift has to compile it.
You should run Swiften's swiften-config tool as part of your build system, which will tell you which libraries need to be linked in for the particular way Swiften's been built on that machine.

In your case, it would have told you the system Boost libraries that were used and needed to be linked, and wouldn't have said Swiften_Boost.

Closing this as I think it's clear at this point that the bug isn't in Swiften.

**Closed by Kev** 2016-11-17 15:02 UTC

**Comment by LNJ2** [comment] 2016-11-17 15:08
Sorry and Thank you guys. :)
